doble_nacionalidad/urls.py
from django.urls import path

# Se importan las vistas a llamar en esta aplicación
# del proyecto 
from . import views

app_name = 'doble_nacionalidad'

urlpatterns = [
    #URLS de Doble nacionalidad
    path('',views.ListaDobleNacionalidad.as_view(),name='lista'),
    path('nuevo/',views.NuevaDobleNacionalidad.as_view(),name='nuevo'),
    # path('detalle/<str:pk>',views.DetalleDobleNacionalidad.as_view(),name='detalle'),
    # path('editar/<str:pk>',views.EditarDobleNacionalidad.as_view(),name='editar'),
    # path('eliminar/<str:pk>',views.EliminarDobleNacionalidad.as_view(),name='eliminar'),

]

sezamidesk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('consultas.urls')),
    path('apostillas/',include('apostillas.urls')),
    path('tramites/',include('tramites.urls')),
    path('beneficiarios/', include('beneficiarios.urls')),
    path('empleados/',include('empleados.urls')),
    path('localizacion-personas/',include('localizacion_personas.urls')),
    path('atencion-migrantes/',include('atencion_migrantes.urls')),
    path('visas/',include('visas.urls')),
    path('corazon-plata/',include('corazon_plata.urls')),
    path('catalogos/',include('catalogos.urls')),
    path('pasaportes/',include('pasaportes_seguros.urls_pasaportes')),
    path('seguros/',include('pasaportes_seguros.urls_seguros')),
    path('traslado-cuerpos/',include('traslado_cuerpos.urls')),

    #Ferias binacionales
    path('constancia-estudios/',include('constancia_estudio.urls')),
    path('licencia-conducir/',include('licencia_conducir.urls')),
    path('mandamientos-judiciales/',include('mandamientos_judiciales.urls')),
    path('defensoria-publica/',include('defensoria_publica.urls')),
    path('correccion-acta/',include('correccion_acta.urls')),
    path('expedicion-acta/',include('expedicion_acta.urls')),
    path('doble-nacionalidad/',include('doble_nacionalidad.urls')),

]

visas/urls.py
from django.urls import path
from . import views

app_name = 'visas'

urlpatterns = [
    path('',views.ListaVisa.as_view(),name='lista'),
    path('nueva/',views.NuevaVisa.as_view(),name='nueva'),
    path('detalle/<int:pk>',views.DetalleVisa.as_view(),name='detalle'),
    path('editar/<int:pk>',views.EditarVisa.as_view(),name='editar'),
    path('eliminar/<int:pk>',views.EliminarVisa.as_view(),name='eliminar'),
]

doble_nacionalidad/models.py
from django.db import models
from django.core.validators import RegexValidator

def autoincremento_folio(): 
    incremento = DobleNacionalidad.objects.all().order_by('folio').last()
    if not incremento:
        # Si la tabla no tiene registros regresamos el valor inicial del folio
        return 400000000 # 100000000 Es el valor inicial del folio
    return incremento.folio + 1

class DobleNacionalidad(models.Model):
    folio = models.IntegerField('folio', primary_key=True, default=autoincremento_folio)
    nombre = models.CharField('Nombre',max_length=50)
    apellido_paterno = models.CharField('Apellido paterno',max_length=50)
    apellido_materno = models.CharField('Apellido materno',max_length=50,blank=True, null=True)
    acta_nacimiento_original = models.BooleanField("Acta de Nacimiento Original",default=False)
    actas_apostilladas = models.BooleanField("Actas apostilladas",default=False)
    comprobante_domicilio = models.BooleanField("Comprobante de domicilio",default=False)
    identificacion_oficial = models.BooleanField("Identificación Oficial Padres",default=False)
    original_copias = models.BooleanField("Original y 2 Copias tama",default=False) 
    tramite_estado = models.ForeignKey('tramites.EstadoTramite',verbose_name='Estado trámite',on_delete=models.CASCADE, null=True)   
    empleado = models.ForeignKey("empleados.Empleado",verbose_name='Empleado',on_delete=models.CASCADE)

doble_nacionalidad/forms.py
from django import forms 
from .models import *
from django.contrib.auth.forms import UserCreationForm


class DobleNacionalidadForm(forms.ModelForm):   
    def __init__(self, *args, **kwargs):
        super(DobleNacionalidadForm, self).__init__(*args, **kwargs)
        self.fields['tramite_estado'].initial = 1
    
    def __init__(self, *args, **kwargs):
        super(DobleNacionalidadForm, self).__init__(*args, **kwargs)
        self.fields['empleado'].required = False

    class Meta:
        model = DobleNacionalidad
        fields = '__all__'
        widgets = {   
            'folio':forms.HiddenInput(attrs={'class':'form-control','placeholder':'Folio'}),
            'nombre':forms.TextInput(attrs={'class':'form-control','placeholder':'Nombre'}),
            'apellido_paterno':forms.TextInput(attrs={'class':'form-control','placeholder':'Apellido paterno'}),
            'apellido_materno':forms.TextInput(attrs={'class':'form-control','placeholder':'Apellido materno'}),
            'acta_nacimiento_original':forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),
            'actas_apostilladas':forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),
            'comprobante_domicilio':forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),
            'identificacion_oficial':forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),          
            'original_copias': forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}), 
            'tramite_estado':forms.TextInput(attrs={'hidden':'hidden'}),
            'empleado':forms.HiddenInput(attrs={'class':'form-control'}) 
        } 

doble_nacionalidad/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from .forms import *
from .models import * 
from empleados.models import Empleado
from beneficiarios.models import *
from beneficiarios.forms import *
from catalogos.forms import *

class ListaDobleNacionalidad(ListView,PermissionRequiredMixin):
    permission_required = 'defensoria_publica.view_defensoria_publica'
    model = DobleNacionalidad
    context_object_name = 'doble_nacionalidad'
    extra_context = {'app':'doble_nacionalidad:lista',
                     'color':'#b4ddc9'}
    
    def get(self,request,*args,**kwargs):
        # Se obtiene el usuario logueado
        usuario = get_object_or_404(Empleado,username=request.user.username)
        # Se obtiene el grupo al que pertenece el usuario (Super Admin, Admin o Capturista)
        grupo_usuario = usuario.grupo_id
        if grupo_usuario == 3 or grupo_usuario == 2:
            # Es Super Admin o admin  
            return super().get(request,*args,**kwargs)  
        else:
            # Es capturista, se muestran solamente los trámites que el usuario ha realizado
            lista_defensoria_publica = DobleNacionalidad.objects.filter(tramite__empleado_id=usuario.id)
            # Se obtiene asigna el context_object_name definido 
            self.object_list = self.get_queryset()
            # Se agregan los trámites filtrados a la lista de variables a pasar al template
            context = self.get_context_data()
            context['defensoria_publica'] = lista_defensoria_publica
            return self.render_to_response(context)

class NuevaDobleNacionalidad(CreateView): # Esta clase se utiliza para crear nuevos registros de doble nacionalidad
    model = DobleNacionalidad
    form_class = DobleNacionalidadForm
    extra_context = {'etiqueta':'Registrar','boton':'Registrar'}
    success_url = reverse_lazy('doble_nacionalidad:lista') # Nos redirecciona a la lista de personas desaparecidas

    

    def form_valid(self, form):
        self.persona = form.save(commit=False)
        # Se obtiene los datos del empleado que esta realizando el registro
        empleado = get_object_or_404(Empleado,username=self.request.user.username)
        # Se guarda en el registro de la persona desaparecida al empleado que realizo el registro
        self.persona.empleado = empleado
        self.persona.save()
        messages.success(self.request,'¡Registro guardado exitosamente!')
        return super(NuevaDobleNacionalidad, self).form_valid(form)

    def form_invalid(self,form):
        print(form.errors)

doble_nacionalidad/templates/doble_nacionalidad/doblenacionalidad_form.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Doble nacionalidad
{% endblock %}

{% block colorFondo %}style="background-color: #b4ddc9;"{% endblock colorFondo %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/formulario.css' %}">
{% endblock %}

{% block encabezado %} 
    Trámite de doble nacionalidad
{% endblock %}
{% block contenido %}
<form method="POST">
    {% csrf_token %}
    {{form.folio}}
    {{form.empleado}}
    {{form.tramite_estado}}
    <section>
        <div class="container">
	    <p style="display: inline;"><b>Datos del trámite</b></p>
            <hr>
            <p style="display: inline;">
                <p>
                    <label for="id_nombre">Nombre</label> 
                    {{form.nombre}}
                </p>
                <p>
                    <label for="id_apellido_paterno">Apellido paterno</label> 
                    {{form.apellido_paterno}}
                </p>
                <p>
                    <label for="id_apellido_materno">Apellido materno </label> 
                    {{form.apellido_materno}}
                </p>
                <p>
                    {{form.acta_nacimiento_original}}
                    <label for="id_acta_nacimiento_original">Acta de nacimiento original y expedición reciente </label> 
                </p>
                <p>
                    {{form.actas_apostilladas}}
                    <label for="id_actas_apostilladas">Actas debidamente apostilladas (del interesado) </label> 
                </p>
                <p>
                    {{form.comprobante_domicilio}}
                    <label for="id_comprobante_domicilio">Comprobante de domicilio </label> 
                </p>
                <p>
                    {{form.identificacion_oficial}}
                    <label for="id_identificacion_oficial">Identificación oficial con fotografía de los padres</label> 
                </p>
                <p>
                    {{form.original_copias}}
                    <label for="id_original_copias">Original y 2 copias tamaño carta </label> 
                </p>
            </p>
        </div>
    </section>
    <div id="prev">
        <a class="btn btn-secondary btn-lg" href="{% url 'doble_nacionalidad:lista' %}" name="botones-formulario">Regresar</a>    
        <input type="submit" class="btn btn-primary btn-lg" id="submit" value="{% if editar == False %}Agregar{% else %}Guardar{% endif %}" name="botones-formulario">
    </div>
</form>
<br>
{% endblock %}
{% block js %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static 'js/tramites.js' %}"></script>
{% endblock %}

doble_nacionalidad/templates/doble_nacionalidad/doblenacionalidad_list.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Doble nacionalidad
{% endblock %}

{% block colorFondo %}style="background-color: #b4ddc9;"{% endblock colorFondo %}

{% block encabezado %} 
    <div class="container">
        <!-- Se muestran los mensajes correspondientes a las acciones realizadas (Nuevo registro, eliminación de registro,
        actualización de registro, eliminación de registro, etc), los mensajes pueden ser de tipo success, error, o de tipo info. -->
        {% block mensajes %}    
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'success',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'Aceptar'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'error',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'Aceptar'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'info',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'Aceptar'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endblock mensajes %}

        <div class="row align-items-center justify-content-between">
            <div class="col-md-9">
                Doble nacionalidad
            </div>
            <div class="col-md-auto">
                <a class="btn btn-primary btn-lg" href="{% url 'doble_nacionalidad:nuevo' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                </svg>
                Nuevo registro
                </a>
            </div>
        </div>
    </div> 
{% endblock %}
{% block contenido %}
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Información de doble nacionalidad
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Folio</th>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th>Estado del trámite</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Folio</th>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th>Estado del trámite</th>
                        <th>Opciones</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for nacionalidad in object_list %}
                    <tr {% if nacionalidad.tramite_estado.id == 1 %} style="background-color: #df5d66d7;" 
                        {% elif nacionalidad.tramite_estado.id == 2 %} style="background-color: #47b4e6d8;" 
                        {% elif nacionalidad.tramite_estado.id == 3 %} style="background-color: #ead249d5;" 
                        {% else %} style="background-color: #3fd61962;" {% endif %}>
                        <td>{{nacionalidad.folio}}</td>
                        <td>{{nacionalidad.nombre}}</td>
                        <td>{{nacionalidad.primer_apellido}} {{nacionalidad.segundo_apellido}}</td>
                        <td>{{nacionalidad.tramite_estado}}</td>
                            
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Formulario que se utiliza para eliminar un registro especifico -->
    <form id="formEliminarRegistro" method="POST">
        {% csrf_token %}
    </form>
{% endblock %}

{% block js %}
    <script src="{% static 'js/modales.js' %}"></script>
{% endblock %}