expedicion_acta/urls.py
from django.urls import path

# Se importan las vistas a llamar en esta aplicación
# del proyecto 
from . import views

app_name = 'expedicion_acta'

urlpatterns = [
    #URLS generales de licencia de conducir
    path('pedir-curp/',views.pedir_curp,name='pedir_curp'),
    path('verificar-curp/', views.verificar_curp, name='verificar_curp'),
    path('completar/<int:pk>', views.EditarExpedicionActa.as_view(), name='completar'),

    #URLS de licencia de conducir
    path('',views.ListaExpedicionActa.as_view(),name='lista'),
    path('nuevo/',views.NuevaExpedicionActa.as_view(),name='nuevo'),
    path('detalle/<int:pk>',views.DetalleExpedicionActa.as_view(),name='detalle'),
    path('editar/<int:pk>',views.EditarExpedicionActa.as_view(),name='editar'),
    path('eliminar/<int:pk>',views.EliminarExpedicionActa.as_view(),name='eliminar'),

]

sezamidesk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('consultas.urls')),
    path('apostillas/',include('apostillas.urls')),
    path('tramites/',include('tramites.urls')),
    path('beneficiarios/', include('beneficiarios.urls')),
    path('empleados/',include('empleados.urls')),
    path('localizacion-personas/',include('localizacion_personas.urls')),
    path('atencion-migrantes/',include('atencion_migrantes.urls')),
    path('visas/',include('visas.urls')),
    path('corazon-plata/',include('corazon_plata.urls')),
    path('catalogos/',include('catalogos.urls')),
    path('pasaportes/',include('pasaportes_seguros.urls_pasaportes')),
    path('seguros/',include('pasaportes_seguros.urls_seguros')),
    path('traslado-cuerpos/',include('traslado_cuerpos.urls')),

    #Ferias binacionales
    path('constancia-estudios/',include('constancia_estudio.urls')),
    path('licencia-conducir/',include('licencia_conducir.urls')),
    path('mandamientos-judiciales/',include('mandamientos_judiciales.urls')),
    path('defensoria-publica/',include('defensoria_publica.urls')),
    path('correccion-acta/',include('correccion_acta.urls')),
    path('expedicion-acta/',include('expedicion_acta.urls')),
    path('doble-nacionalidad/',include('doble_nacionalidad.urls')),

]

tramites/urls.py
from django.urls import path
# Se importan las vistas a llamar en esta aplicación
# del proyecto 
from . import views

app_name = 'tramites'

urlpatterns = [
    path('lista/',views.TramiteList.as_view(), name = 'lista_tramite'),
    path('pedir-curp',views.pedir_curp,name='pedir_curp'),
    path('editar/<int:pk>',views.TramiteEditar.as_view(),name='editar'),
    path('actualizar-estatus/<int:pk>',views.actualizar_tramite,name='actualizar'),
    path('actualizar/<int:pk>',views.guardar_acualizacion,name='guardar_acualizacion'),
    path('eliminar/<int:pk>',views.TramiteEliminar.as_view(),name='eliminar'),
    path('ferias-binacionales/',views.ferias_binacionales,name='ferias_binacionales'),
]

visas/urls.py
from django.urls import path
from . import views

app_name = 'visas'

urlpatterns = [
    path('',views.ListaVisa.as_view(),name='lista'),
    path('nueva/',views.NuevaVisa.as_view(),name='nueva'),
    path('detalle/<int:pk>',views.DetalleVisa.as_view(),name='detalle'),
    path('editar/<int:pk>',views.EditarVisa.as_view(),name='editar'),
    path('eliminar/<int:pk>',views.EliminarVisa.as_view(),name='eliminar'),
]

expedicion_acta/models.py
from django.db import models
from django.core.validators import RegexValidator

class ExpedicionActa(models.Model):
    curp = models.CharField("CURP", default = "", max_length=18, validators=[RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\d)')])
    nombre_solicitante = models.CharField("Nombre del solicitante", max_length=100)
    fecha_nacimiento = models.DateField("Fecha de nacimiento", null=True, blank=True)
    municipio_registro = models.ForeignKey('catalogos.Municipio',verbose_name="Municipio",on_delete=models.CASCADE, null=True)
    tramite = models.ForeignKey('tramites.Tramite',verbose_name='Trámite',on_delete=models.CASCADE)

expedicion_acta/forms.py
from django import forms 
from .models import *

class DateInput(forms.DateInput):
    input_type = 'date'


class ExpedicionActaForm(forms.ModelForm):   
    fecha_nacimiento = forms.DateField(label='Fecha de nacimiento',
    widget=DateInput(
        format='%Y-%m-%d',
        attrs={'class':'form-control elemento-tramite','placeholder':'Fecha de nacimiento'}),
        required=True)    
    class Meta:
        model = ExpedicionActa
        fields = '__all__'
        widgets = {   
            'curp':forms.TextInput(attrs={'class':'form-control', 'readonly':'readonly'}),
            'nombre_solicitante': forms.TextInput(attrs={'class':'form-control elemento-tramite'}),
            'municipio_registro': forms.Select(attrs={'class':'form-control elemento-tramite'}),
            'tramite':forms.TextInput(attrs={'class':'form-control','hidden':'hidden'})  
        }

expedicion_acta/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from .forms import *
from .models import * 
from tramites.models import Tramite
from tramites.forms import PedirCurpForm
from empleados.models import Empleado
from beneficiarios.models import *
from beneficiarios.forms import *
from catalogos.forms import *
from tramites.validators import validar_curp

def pedir_curp(request):
    if request.method == "GET":
        form = PedirCurpForm()
        extra_context = {'form':form,
                         'anterior':'expedicion_acta:lista',
                         'app':'expedicion_acta:verificar_curp',
                         'feria_binacional':True,
                         'feria_app':'a expedición de acta'}
        return render(request,'tramites/pedir_curp.html',extra_context)

def verificar_curp(request):
    # Se obtiene la CURP ingresada por el usuario
    curp = request.POST['curp']
    if validar_curp(curp):
        # Se verifica si hay un trámite pendiente con la curp indicada
        expedicion_acta = ExpedicionActa.objects.filter(curp=curp).last()
        
        if expedicion_acta == None:
            # No existe ningún trámite con la curp indicada. Se crea uno nuevo
            return nuevo_tramite(request,curp)
        else:
            # Ya existe algún trámite con la curp indicada
            tramite = get_object_or_404(Tramite,id=expedicion_acta.tramite_id)
            if tramite.estado_id == 1:
                # Se continúa con el trámite encontrado para registrar sus documentos faltantes
                return HttpResponseRedirect('/expedicion-acta/completar/' + str(expedicion_acta.id))
            else:
                # Ya se había solicitado con anterioridad una constancia de estudio. 
                # Se crea una nueva solicitud
                return nuevo_tramite(request,curp)
    else:
        messages.error(request,'Por favor introduzca una CURP válida')
        return redirect('expedicion_acta:pedir_curp')

def nuevo_tramite(request,curp):
    # Creación del proceso trámite
    tramite = Tramite()
    tramite.estado_id = 1
    empleado = get_object_or_404(Empleado,username=request.user.username)
    tramite.empleado_id = empleado.id
    # Se verifica, en base a la CURP, si la información del beneficiario ya ha sido capturada.
    if Beneficiario.objects.filter(curp=curp).first() != None:
        # Los datos del beneficiario ya se encuentran capturados en el sistema
        # Se agrega la curp al proceso del trámite
        tramite.beneficiario_id = curp
        
    tramite.save()
    tramite = Tramite.objects.latest('id')

    # Creación trámite específico
    expedicion_acta = ExpedicionActa()
    expedicion_acta.curp = curp
    expedicion_acta.tramite_id = tramite.id
    expedicion_acta.municipio_id = 1
    expedicion_acta.save()
    expedicion_acta = ExpedicionActa.objects.get(id=expedicion_acta.id)
    return HttpResponseRedirect('/expedicion-acta/completar/' + str(expedicion_acta.id))

class ListaExpedicionActa(ListView,PermissionRequiredMixin):
    permission_required = 'expedicion_acta.view_expedicionacta'
    model = ExpedicionActa
    context_object_name = 'expedicion_acta'
    extra_context = {'app':'expedicion_acta:lista',
                     'color':'#b4ddc9'}
    
    def get(self,request,*args,**kwargs):
        # Se obtiene el usuario logueado
        usuario = get_object_or_404(Empleado,username=request.user.username)
        # Se obtiene el grupo al que pertenece el usuario (Super Admin, Admin o Capturista)
        grupo_usuario = usuario.grupo_id
        if grupo_usuario == 3 or grupo_usuario == 2:
            # Es Super Admin o admin  
            return super().get(request,*args,**kwargs)  
        else:
            # Es capturista, se muestran solamente los trámites que el usuario ha realizado
            lista_expedicion_acta = ExpedicionActa.objects.filter(tramite__empleado_id=usuario.id)
            # Se obtiene asigna el context_object_name definido 
            self.object_list = self.get_queryset()
            # Se agregan los trámites filtrados a la lista de variables a pasar al template
            context = self.get_context_data()
            context['expedicion_acta'] = lista_expedicion_acta
            return self.render_to_response(context)

class NuevaExpedicionActa(CreateView,PermissionRequiredMixin):
    permission_required = 'expedicion_acta.add_expedicionacta'
    model = ExpedicionActa
    form_class = ExpedicionActaForm
    extra_context = {'editar': False}
    success_url = reverse_lazy('expedicion_acta:lista')

class DetalleExpedicionActa(DetailView,PermissionRequiredMixin):
    permission_required = 'expedicion_acta.view_expedicionacta'
    model = ExpedicionActa
    context_object_name = 'expedicion_acta'
    extra_context = {'app':'expedicion_acta:lista'}

class EliminarExpedicionActa(DeleteView,PermissionRequiredMixin):
    permission_required = 'expedicion_acta.delete_expedicionacta'
    model = ExpedicionActa

    def post(self,request,*args,**kwargs):
        # Se elimina el proceso del tramite que internamente elimina el
        # registro en la tabla de constancia estudios
        tramite_id = kwargs['pk']
        tramite = get_object_or_404(Tramite,id=tramite_id)
        tramite.delete()
        messages.success(self.request,'¡Registro eliminado exitosamente!')
        return redirect('expedicion_acta:lista')

class EditarExpedicionActa(UpdateView,PermissionRequiredMixin):
    permission_required = 'expedicion_acta.change_expedicionacta'
    model = ExpedicionActa
    form_class = ExpedicionActaForm
    form_beneficiario = BeneficiarioForm
    extra_context = {
        'boton':'Guardar',
        'form_beneficiario':form_beneficiario,
        'template_tramite':'expedicion_acta/expedicionacta.html',
        'feria_binacional': True
    }

    def get(self,request,*args,**kwargs):
        self.object = self.get_object()
        expedicion_acta = self.object
        context = self.get_context_data()
        curp = expedicion_acta.curp 

        beneficiario = Beneficiario.objects.filter(curp=curp).first()
        if beneficiario != None:
            # Los datos del beneficiario ya habían sido capturados, por lo tanto, se llenan
            # los campos del formulario automáticamente
            form_beneficiario = BeneficiarioForm(instance=beneficiario)
            context['form_beneficiario'] = form_beneficiario
            context['url_beneficiario'] = 'beneficiarios:editar_feria' 
            context['id_beneficiario'] = curp 
        else:
            context['url_beneficiario'] = 'beneficiarios:crear_feria'
        # Indica la sección del sistema a la que se desea regresar una vez guardado el trámite
        context['app'] = 'expedicion_acta:lista'
        return self.render_to_response(context)

    
    def post(self,request,*args,**kwargs):
        campos_obligatorios = ['nombre_solicitante','fecha_nacimiento','municipio_registro']
        datos = request.POST
        for campo in datos:
            if (campo in campos_obligatorios) and (datos[campo] == ''):
                # Alguno de los campos obligatorios no tienen ningún dato capturado, por tanto,
                # no se puede proceder a llenar los datos del beneficiario.
                # Los datos son válidos, pero faltaron documentos por entregar
                messages.success(self.request,'¡Registro guardado exitosamente!')
                super().post(request,*args,**kwargs)
                return redirect('expedicion_acta:lista')
        # Los datos son válidos, pero faltaron documentos por entregar
        return super().post(request,*args,**kwargs)

    def get_success_url(self):
        return self.request.path

expedicion_acta/templates/expedicion_acta/expedicionacta_form.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Expedición de acta
{% endblock %}

{% block colorFondo %}style="background-color: #b4ddc9;"{% endblock colorFondo %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/formulario.css' %}">
{% endblock %}

{% block encabezado %} 
    Trámite de expedición de acta
{% endblock %}
{% block contenido %}
<form method="POST" id="tramite">
    {% csrf_token %}
    <div id="svg_wrap">
    </div>
    <section>
        <div class="container">
	    <p style="display: inline;"><b>Datos del trámite</b></p>
            <hr>
            <p style="display: inline;">
                <p>
                    {{form.curp}}
                </p>
                <p>
                    <label for="id_nombre_solicitante">Nombre del solicitante </label> 
                    {{form.nombre_solicitante}}
                </p>
                <p>
                    <label for="id_fecha_nacimiento">Fecha de nacimiento</label> 
                    {{form.fecha_nacimiento}}
                </p>
                <p>
                    <label for="id_municipio_registro">Municipio de registro</label> 
                    {{form.municipio_registro}}
                </p>
                {{form.tramite}}
            </p>
        </div>
    </section>
    <div id="prev">
        <a class="btn btn-secondary btn-lg" href="{% url 'expedicion_acta:lista' %}" name="botones-formulario">Regresar</a>    
        <input type="submit" class="btn btn-primary btn-lg" id="submit" value="{% if editar == False %}Agregar{% else %}Guardar{% endif %}" name="botones-formulario">
    </div>
</form>
<br>
{% include 'beneficiarios/beneficiario_global.html' %}
{% endblock %}
{% block js %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static 'js/tramites.js' %}"></script>
{% endblock %}

expedicion_acta/templates/expedicion_acta/expedicionacta_list.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Expedición de acta
{% endblock %}

{% block colorFondo %}style="background-color: #b4ddc9;"{% endblock colorFondo %}

{% block encabezado %} 
    <div class="container">
        <!-- Se muestran los mensajes correspondientes a las acciones realizadas (Nuevo registro, eliminación de registro,
        actualización de registro, eliminación de registro, etc), los mensajes pueden ser de tipo success, error, o de tipo info. -->
        {% block mensajes %}    
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'success',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'Aceptar'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'error',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'Aceptar'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'info',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'Aceptar'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endblock mensajes %}

        <div class="row align-items-center justify-content-between">
            <div class="col-md-9">
                Expedición de acta
            </div>
            <div class="col-md-auto">
                <a class="btn btn-primary btn-lg" href="{% url 'expedicion_acta:pedir_curp' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                </svg>
                Nuevo registro
                </a>
            </div>
        </div>
    </div> 
{% endblock %}
{% block contenido %}
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Información de expedición de acta
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>CURP</th>
                        <th>Primer Apellido</th>
                        <th>Segundo Apellido</th>
                        <th>Nombre(s)</th>
                        <th>Estado del trámite</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>CURP</th>
                        <th>Primer Apellido</th>
                        <th>Segundo Apellido</th>
                        <th>Nombre(s)</th>
                        <th>Estado del trámite</th>
                        <th>Acciones</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for expedicion in object_list %}
                    <tr {% if expedicion.tramite.estado_id == 1 %} style="background-color: #df5d66d7;" 
                        {% elif expedicion.tramite.estado_id == 2 %} style="background-color: #47b4e6d8;" 
                        {% elif expedicion.tramite.estado_id == 3 %} style="background-color: #ead249d5;" 
                        {% else %} style="background-color: #3fd61962;" {% endif %}>
                        <td>{{expedicion.curp}}</td>
                        {% if expedicion.tramite.beneficiario_id == None %}
                            <td>Sin capturar</td>
                            <td>Sin capturar</td>
                            <td>Sin capturar</td>
                        {% else %}
                            <td>{{expedicion.tramite.beneficiario.primer_apellido}}</td>
                            <td>{{expedicion.tramite.beneficiario.segundo_apellido}}</td>
                            <td>{{expedicion.tramite.beneficiario.nombre}}</td>
                        {% endif %}
                        <td>{{expedicion.tramite.estado}}</td>
                            <td>
                                <div class="container">
                                    <div class="row justify-content-center">
                                        <div class="col-3">
                                            <a class="btn btn-success btn-sm" href="{% url 'expedicion_acta:detalle' expedicion.id %}">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                                                </svg>
                                            </a>
                                        </div>
                                        <div class="col-3">
                                            {% if expedicion.tramite.estado_id != 1 %}
                                                {% if perms.expedicion_acta.change_expedicionacta %}
                                                    <form action="{% url 'tramites:actualizar' expedicion.tramite.id %}" method="post">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="app" value="{{app}}">
                                                        <input type="hidden" name="color" value="{{color}}">
                                                        <button type="submit" class="btn btn-warning btn-sm" id="submit" value="Editar" name="botones-formulario">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                            </svg>
                                                        </button>
                                                    </form>
                                                {% endif %}   
                                            {% else %}
                                                {% if perms.expedicion_acta.change_expedicionacta %}
                                                    <a class="btn btn-warning btn-sm" href="{% url 'expedicion_acta:completar' expedicion.id %}">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                        </svg>
                                                    </a>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                        {% if perms.expedicion_acta.delete_expedicionacta %}
                                            <div class="col-3">
                                                <button onclick="eliminarRegistro('{% url 'expedicion_acta:eliminar' expedicion.tramite.id %}')" type="button" class="btn btn-danger btn-sm">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                    </svg>
                                                </button>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <a class="btn btn-secondary btn-lg" href="{% url 'tramites:ferias_binacionales' %}">Regresar a ferias binacionales</a>   
    <!-- Formulario que se utiliza para eliminar un registro especifico -->
    <form id="formEliminarRegistro" method="POST">
        {% csrf_token %}
    </form>
{% endblock %}

{% block js %}
    <script src="{% static 'js/modales.js' %}"></script>
{% endblock %}