mandamientos_judiciales/urls.py
from django.urls import path

# Se importan las vistas a llamar en esta aplicación
# del proyecto 
from . import views

app_name = 'mandamientos_judiciales'

urlpatterns = [
    #URLS generales de mandamientos judiciales
    path('pedir-curp/',views.pedir_curp,name='pedir_curp'),
    path('verificar-curp/', views.verificar_curp, name='verificar_curp'),
    path('completar/<int:pk>', views.EditarMandamientosJudiciales.as_view(), name='completar'),

    # URLS de Mandamientos judiciales
    path('',views.ListaMandamientosJudiciales.as_view(),name='lista'),
    path('nuevo/',views.NuevaMandamientosJudiciales.as_view(),name='nuevo'),
    path('detalle/<int:pk>',views.DetalleMandamientosJudiciales.as_view(),name='detalle'),
    path('editar/<int:pk>',views.EditarMandamientosJudiciales.as_view(),name='editar'),
    path('eliminar/<int:pk>',views.EliminarMandamientosJudiciales.as_view(),name='eliminar'),

]

sezamidesk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('consultas.urls')),
    path('apostillas/',include('apostillas.urls')),
    path('tramites/',include('tramites.urls')),
    path('beneficiarios/', include('beneficiarios.urls')),
    path('empleados/',include('empleados.urls')),
    path('localizacion-personas/',include('localizacion_personas.urls')),
    path('atencion-migrantes/',include('atencion_migrantes.urls')),
    path('visas/',include('visas.urls')),
    path('corazon-plata/',include('corazon_plata.urls')),
    path('catalogos/',include('catalogos.urls')),
    path('pasaportes/',include('pasaportes_seguros.urls_pasaportes')),
    path('seguros/',include('pasaportes_seguros.urls_seguros')),
    path('traslado-cuerpos/',include('traslado_cuerpos.urls')),

    #Ferias binacionales
    path('constancia-estudios/',include('constancia_estudio.urls')),
    path('licencia-conducir/',include('licencia_conducir.urls')),
    path('mandamientos-judiciales/',include('mandamientos_judiciales.urls')),
    path('defensoria-publica/',include('defensoria_publica.urls')),
    path('correccion-acta/',include('correccion_acta.urls')),
    path('expedicion-acta/',include('expedicion_acta.urls')),
    path('doble-nacionalidad/',include('doble_nacionalidad.urls')),

]

tramites/urls.py
from django.urls import path
# Se importan las vistas a llamar en esta aplicación
# del proyecto 
from . import views

app_name = 'tramites'

urlpatterns = [
    path('lista/',views.TramiteList.as_view(), name = 'lista_tramite'),
    path('pedir-curp',views.pedir_curp,name='pedir_curp'),
    path('editar/<int:pk>',views.TramiteEditar.as_view(),name='editar'),
    path('actualizar-estatus/<int:pk>',views.actualizar_tramite,name='actualizar'),
    path('actualizar/<int:pk>',views.guardar_acualizacion,name='guardar_acualizacion'),
    path('eliminar/<int:pk>',views.TramiteEliminar.as_view(),name='eliminar'),
    path('ferias-binacionales/',views.ferias_binacionales,name='ferias_binacionales'),
]

visas/urls.py
from django.urls import path
from . import views

app_name = 'visas'

urlpatterns = [
    path('',views.ListaVisa.as_view(),name='lista'),
    path('nueva/',views.NuevaVisa.as_view(),name='nueva'),
    path('detalle/<int:pk>',views.DetalleVisa.as_view(),name='detalle'),
    path('editar/<int:pk>',views.EditarVisa.as_view(),name='editar'),
    path('eliminar/<int:pk>',views.EliminarVisa.as_view(),name='eliminar'),
]

mandamientos_judiciales/models.py
from django.db import models
from django.core.validators import RegexValidator

class MandamientosJudiciales(models.Model):
    curp = models.CharField("CURP", default = "", max_length=18, validators=[RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\d)')])
    acta_nac_original = models.BooleanField("Acta de Nacimiento Original",default=False) 
    curp_act = models.BooleanField("CURP Actualizada",default=False) 
    comprobante_domicilio = models.BooleanField("Comprobante domicilio",default=False) 
    pasaporte_vigente = models.BooleanField("Pasaporte vigente",default=False) 
    matricula_consular = models.BooleanField("Matrícula Consular",default=False) 
    pago_en_caja_fiscalia = models.BooleanField("Pago que se realiza en caja de fiscalía",default=False) 
    fotografia= models.BooleanField("Fotografía tamaño infantil blanco y negro con fondo blanco",default=False) 
    ine_familiar = models.BooleanField("INE del familiar directo que va a tramitar el documento",default=False) 
    tramite = models.ForeignKey('tramites.Tramite',verbose_name='Trámite',on_delete=models.CASCADE)

mandamientos_judiciales/forms.py
from django import forms 
from .models import *

class MandamientosJudicialesForm(forms.ModelForm):   
    class Meta:
        model = MandamientosJudiciales
        fields = '__all__'
        widgets = {   
            'curp':forms.TextInput(attrs={'class':'form-control', 'readonly':'readonly'}),
            'acta_nac_original':forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),
            'curp_act':forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),
            'comprobante_domicilio':forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),          
            'pasaporte_vigente': forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),  
            'matricula_consular': forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),  
            'pago_en_caja_fiscalia':forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),          
            'fotografia': forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),  
            'ine_familiar': forms.CheckboxInput(attrs={'class':'form-check-input elemento-tramite'}),  
            'tramite':forms.TextInput(attrs={'class':'form-control','hidden':'hidden'})   
        }

mandamientos_judiciales/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from .forms import *
from .models import * 
from tramites.models import Tramite
from tramites.forms import PedirCurpForm
from empleados.models import Empleado
from beneficiarios.models import *
from beneficiarios.forms import *
from catalogos.forms import *
from tramites.validators import validar_curp

def pedir_curp(request):
    if request.method == "GET":
        form = PedirCurpForm()
        extra_context = {'form':form,
                         'anterior':'mandamientos_judiciales:lista',
                         'app':'mandamientos_judiciales:verificar_curp',
                         'feria_binacional':True,
                         'feria_app':'a mandamientos judiciales'}
        return render(request,'tramites/pedir_curp.html',extra_context)

def verificar_curp(request):
    # Se obtiene la CURP ingresada por el usuario
    curp = request.POST['curp']
    if validar_curp(curp):
        # Se verifica si hay un trámite pendiente con la curp indicada
        mandamientos_judiciales = MandamientosJudiciales.objects.filter(curp=curp).last()
        
        if mandamientos_judiciales == None:
            # No existe ningún trámite con la curp indicada. Se crea uno nuevo
            return nuevo_tramite(request,curp)
        else:
            # Ya existe algún trámite con la curp indicada
            tramite = get_object_or_404(Tramite,id=mandamientos_judiciales.tramite_id)
            if tramite.estado_id == 1:
                # Se continúa con el trámite encontrado para registrar sus documentos faltantes
                return HttpResponseRedirect('/mandamientos-judiciales/completar/' + str(mandamientos_judiciales.id))
            else:
                # Ya se había solicitado con anterioridad un mandamiento judicial
                # Se crea una nueva solicitud
                return nuevo_tramite(request,curp)
    else:
        messages.error(request,'Por favor introduzca una CURP válida')
        return redirect('mandamientos_judiciales:pedir_curp')

def nuevo_tramite(request,curp):
    # Creación del proceso trámite
    tramite = Tramite()
    tramite.estado_id = 1
    empleado = get_object_or_404(Empleado,username=request.user.username)
    tramite.empleado_id = empleado.id
    # Se verifica, en base a la CURP, si la información del beneficiario ya ha sido capturada.
    if Beneficiario.objects.filter(curp=curp).first() != None:
        # Los datos del beneficiario ya se encuentran capturados en el sistema
        # Se agrega la curp al proceso del trámite
        tramite.beneficiario_id = curp
        
    tramite.save()
    tramite = Tramite.objects.latest('id')

    # Creación trámite específico
    mandamientos_judiciales = MandamientosJudiciales()
    mandamientos_judiciales.curp = curp
    mandamientos_judiciales.tramite_id = tramite.id
    mandamientos_judiciales.save()
    mandamientos_judiciales = MandamientosJudiciales.objects.get(id=mandamientos_judiciales.id)
    return HttpResponseRedirect('/mandamientos-judiciales/completar/' + str(mandamientos_judiciales.id))


class ListaMandamientosJudiciales(ListView,PermissionRequiredMixin):
    permission_required = 'mandamientos_judiciales.view_mandamientosjudiciales'
    model = MandamientosJudiciales
    context_object_name = 'mandamientos_judiciales'
    extra_context = {'app':'mandamientos_judiciales:lista',
                     'color':'#b4ddc9'}
    
    def get(self,request,*args,**kwargs):
        # Se obtiene el usuario logueado
        usuario = get_object_or_404(Empleado,username=request.user.username)
        # Se obtiene el grupo al que pertenece el usuario (Super Admin, Admin o Capturista)
        grupo_usuario = usuario.grupo_id
        if grupo_usuario == 3 or grupo_usuario == 2:
            # Es Super Admin o admin  
            return super().get(request,*args,**kwargs)  
        else:
            # Es capturista, se muestran solamente los trámites que el usuario ha realizado
            lista_mandamientos_judiciales= MandamientosJudiciales.objects.filter(tramite__empleado_id=usuario.id)
            # Se obtiene asigna el context_object_name definido 
            self.object_list = self.get_queryset()
            # Se agregan los trámites filtrados a la lista de variables a pasar al template
            context = self.get_context_data()
            context['mandamientos_judiciales'] = lista_mandamientos_judiciales
            return self.render_to_response(context)

class NuevaMandamientosJudiciales(CreateView,PermissionRequiredMixin):
    permission_required = 'mandamientos_judiciales.add_mandamientosjudiciales'
    model = MandamientosJudiciales
    form_class = MandamientosJudicialesForm
    extra_context = {'editar': False}
    success_url = reverse_lazy('mandamientos_judiciales:lista')

class DetalleMandamientosJudiciales(DetailView,PermissionRequiredMixin):
    permission_required = 'mandamientos_judiciales.view_mandamientosjudiciales'
    model = MandamientosJudiciales
    context_object_name = 'mandamientos_judiciales'
    extra_context = {'app':'mandamientos_judiciales:lista'}

class EditarMandamientosJudiciales(UpdateView,PermissionRequiredMixin):
    permission_required = 'mandamientos_judiciales.change_mandamientosjudiciales'
    model = MandamientosJudiciales
    form_class = MandamientosJudicialesForm
    form_beneficiario = BeneficiarioForm
    extra_context = {
        'boton':'Guardar',
        'form_beneficiario':form_beneficiario,
        'template_tramite':'mandamientos_judiciales/mandamientosjudiciales_form.html',
        'feria_binacional': True
    }

    def get(self,request,*args,**kwargs):
        self.object = self.get_object()
        mandamientos_judiciales = self.object
        context = self.get_context_data()
        curp = mandamientos_judiciales.curp 

        beneficiario = Beneficiario.objects.filter(curp=curp).first()

        if beneficiario != None:
            # Los datos del beneficiario ya habían sido capturados, por lo tanto, se llenan
            # los campos del formulario automáticamente
            form_beneficiario = BeneficiarioForm(instance=beneficiario)
            context['form_beneficiario'] = form_beneficiario
            context['url_beneficiario'] = 'beneficiarios:editar_feria' 
            context['id_beneficiario'] = curp 
        else:
            context['url_beneficiario'] = 'beneficiarios:crear_feria'
        # Indica la sección del sistema a la que se desea regresar una vez guardado el trámite
        context['app'] = 'mandamientos_judiciales:lista'
        return self.render_to_response(context)

    
    def post(self,request,*args,**kwargs):
        lista_documentos = ['acta_nac_original','curp_act','comprobante_domicilio',
        'pasaporte_vigente','matricula_consular','pago_en_caja_fiscalia','fotografia','ine_familiar'] 
        if all(documento in request.POST for documento in lista_documentos):
            # Todos los documentos del trámite fueron seleccionados.
            # Se guardan, y se continúa en la misma página para capturar
            # los datos del beneficiario
            return super().post(request,*args,**kwargs)
        else:
            # Faltaron documentos por seleccionar
            messages.success(self.request,'¡Registro guardado exitosamente!')
            super().post(request,*args,**kwargs)
            return redirect('mandamientos_judiciales:lista')
       
    def get_success_url(self):
        return self.request.path

class EliminarMandamientosJudiciales(DeleteView,PermissionRequiredMixin):
    permission_required = 'mandamientos_judiciales.delete_mandamientosjudiciales'
    model = MandamientosJudiciales

    def post(self,request,*args,**kwargs):
        # Se elimina el proceso del tramite que internamente elimina el
        # registro en la tabla de mandamientos judiciales
        tramite_id = kwargs['pk']
        tramite = get_object_or_404(Tramite,id=tramite_id)
        tramite.delete()
        messages.success(self.request,'¡Registro eliminado exitosamente!')
        return redirect('mandamientos_judiciales:lista')      

mandamientos_judiciales/templates/mandamientos_judiciales/mandamientosjudiciales_form.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Mandamientos judiciales (Carta de no antecedentes penales)
{% endblock %}

{% block colorFondo %}style="background-color: #b4ddc9;"{% endblock colorFondo %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/formulario.css' %}">
{% endblock %}

{% block encabezado %} 
    Trámite de carta de no antecedentes penales
{% endblock %}
{% block contenido %}
<form method="POST" id="tramite">
    {% csrf_token %}
    <div id="svg_wrap">
    </div>
    <section>
        <div class="container">
            <p style="display: inline;"><b>Datos del trámite</b></p>
            <hr>
            <p style="display: inline;">
                <p>
                    {{form.curp}}
                </p>
                <p>
                    {{form.acta_nac_original}}
                    <label for="id_acta_nac_original">Acta de nacimiento original</label> 
                </p>
                <p>
                    {{form.curp_act}}
                    <label for="id_curp_act">CURP actualizada</label> 
                </p>
                <p>
                    {{form.comprobante_domicilio}}
                    <label for="id_comprobante_domicilio">Comprobante de domicilio</label> 
                </p>
                <p>
                    {{form.pasaporte_vigente}}
                    <label for="id_pasaporte_vigente">Pasaporte vigente</label> 
                </p>
                <p>
                    {{form.matricula_consular}}
                    <label for="id_matricula_consular">Matrícula consular</label> 
                </p>
                <p>
                    {{form.pago_en_caja_fiscalia}}
                    <label for="id_pago_en_caja_fiscalia">Pago que se realiza en caja de fiscalía</label> 
                </p>
                <p>
                    {{form.fotografia}}
                    <label for="id_fotografia">Fotografía tamaño infantil a blanco y negro con fondo blanco</label> 
                </p>
                <p>
                    {{form.ine_familiar}}
                    <label for="id_ine_familiar">INE del familiar directo que tramitó el documento</label> 
                </p>
                {{form.tramite}}
            </p>
        </div>
    </section>
    <div id="prev">
        <a class="btn btn-secondary btn-lg" href="{% url 'mandamientos_judiciales:lista' %}" name="botones-formulario">Regresar</a>    
        <input type="submit" class="btn btn-primary btn-lg" id="submit" value="{% if editar == False %}Agregar{% else %}Guardar{% endif %}" name="botones-formulario">
    </div>
</form>
<br>
{% include 'beneficiarios/beneficiario_global.html' %}
{% endblock %}
{% block js %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static 'js/tramites.js' %}"></script>
{% endblock %}

mandamientos_judiciales/templates/mandamientos_judiciales/mandamientosjudiciales_list.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Registro de mandamientos judiciales (Carta de no antecedentes penales)
{% endblock %}

{% block colorFondo %}style="background-color: #b4ddc9;"{% endblock colorFondo %}

{% block encabezado %} 
    <div class="container">
        <!-- Se muestran los mensajes correspondientes a las acciones realizadas (Nuevo registro, eliminación de registro,
        actualización de registro, eliminación de registro, etc), los mensajes pueden ser de tipo success, error, o de tipo info. -->
        {% block mensajes %}    
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'success',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'Aceptar'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'error',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'Aceptar'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script>
                            Swal.fire({
                                title:'{{message}}',
                                icon:'info',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'Aceptar'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endblock mensajes %}

        <div class="row align-items-center justify-content-between">
            <div class="col-md-9">
                Mandamientos judiciales (Carta de no antecedentes penales)
            </div>
            <div class="col-md-auto">
                <a class="btn btn-primary btn-lg" href="{% url 'mandamientos_judiciales:pedir_curp' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                </svg>
                Nuevo registro
                </a>
            </div>
        </div>
    </div> 
{% endblock %}
{% block contenido %}
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Información de mandamientos judiciales
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>CURP</th>
                        <th>Primer Apellido</th>
                        <th>Segundo Apellido</th>
                        <th>Nombre(s)</th>
                        <th>Estado del trámite</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>CURP</th>
                        <th>Primer Apellido</th>
                        <th>Segundo Apellido</th>
                        <th>Nombre(s)</th>
                        <th>Estado del trámite</th>
                        <th>Acciones</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for mandamiento in object_list %}
                    <tr {% if mandamiento.tramite.estado_id == 1 %} style="background-color: #df5d66d7;" 
                        {% elif mandamiento.tramite.estado_id == 2 %} style="background-color: #47b4e6d8;" 
                        {% elif mandamiento.tramite.estado_id == 3 %} style="background-color: #ead249d5;" 
                        {% else %} style="background-color: #3fd61962;" {% endif %}>
                        <td>{{mandamiento.curp}}</td>
                        {% if mandamiento.tramite.beneficiario_id == None %}
                            <td>Sin capturar</td>
                            <td>Sin capturar</td>
                            <td>Sin capturar</td>
                        {% else %}
                            <td>{{mandamiento.tramite.beneficiario.primer_apellido}}</td>
                            <td>{{mandamiento.tramite.beneficiario.segundo_apellido}}</td>
                            <td>{{mandamiento.tramite.beneficiario.nombre}}</td>
                        {% endif %}
                        <td>{{mandamiento.tramite.estado}}</td>
                            <td>
                                <div class="container">
                                    <div class="row justify-content-center">
                                        <div class="col-3">
                                            <a class="btn btn-success btn-sm" href="{% url 'mandamientos_judiciales:detalle' mandamiento.id %}">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                                                </svg>
                                            </a>
                                        </div>
                                        <div class="col-3">
                                            {% if mandamiento.tramite.estado_id != 1 %}
                                                {% if perms.mandamientos_judiciales.change_mandamientosjudiciales %}
                                                    <form action="{% url 'tramites:actualizar' mandamiento.tramite.id %}" method="post">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="app" value="{{app}}">
                                                        <input type="hidden" name="color" value="{{color}}">
                                                        <button type="submit" class="btn btn-warning btn-sm" id="submit" value="Editar" name="botones-formulario">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                            </svg>
                                                        </button>
                                                    </form>
                                                {% endif %}
                                            {% else %}
                                                {% if perms.mandamientos_judiciales.change_mandamientosjudiciales %}
                                                    <a class="btn btn-warning btn-sm" href="{% url 'mandamientos_judiciales:completar' mandamiento.id %}">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                        </svg>
                                                    </a>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                        {% if perms.mandamientos_judiciales.delete_mandamientosjudiciales %}
                                            <div class="col-3">
                                                <button onclick="eliminarRegistro('{% url 'mandamientos_judiciales:eliminar' mandamiento.tramite.id %}')" type="button" class="btn btn-danger btn-sm">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                    </svg>
                                                </button>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <a class="btn btn-secondary btn-lg" href="{% url 'tramites:ferias_binacionales' %}">Regresar a ferias binacionales</a>   
    <!-- Formulario que se utiliza para eliminar un registro especifico -->
    <form id="formEliminarRegistro" method="POST">
        {% csrf_token %}
    </form>
{% endblock %}

{% block js %}
    <script src="{% static 'js/modales.js' %}"></script>
{% endblock %}